package opsmx

default allow = false

deny[msg]{

    input.metadata.build_image_sha != input.metadata.image_sha
    msg := sprintf("Checksum of image generated by build server does not match with artifact available in artifact repo.", "Ensure that the correct and unaltered artifacts are being used for deployment.")
}
